volumes:
  fastapi-FitCheck-data:
    external: true

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://postgres:f1c8faf839fccf67@srv-captain--fitcheck-db:5432/postgres
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      SIGNING_KEY: 76582974be74df66a4fa4651baef99db21d258bf19557832fcc3b43b911f72e7
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: https://fitcheck.one
      REACT_APP_FitCheck_API_HOST: https://fitcheck-api.dec-ct-3.mod3projects.com
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: f1c8faf839fccf67
      POSTGRES_USER: postgres
      POSTGRES_DB: fitcheck-db
    ports:
      - "15432:5432"
    volumes:
      - fastapi-FitCheck-data:/var/lib/postgresql/data
