volumes:
  fastapi-FitCheck-data:
    external: true

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      SIGNING_KEY: ${SIGNING_KEY}
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_FitCheck_API_HOST: ${REACT_APP_FitCheck_API_HOST}
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: fitcheck-db
    ports:
      - "15432:5432"
    volumes:
      - fastapi-FitCheck-data:/var/lib/postgresql/data
